"""
Regenerates two specific songs and splices them into the existing demoData.js.
"""

import json
import httpx
import pathlib
import re

API = "http://localhost:8000"

REPLACEMENTS = {
    "Funkadelic - Maggot Brain": "Limp Bizkit - It'll Be OK",
    "My Bloody Valentine - Only Shallow": "INXS - Original Sin",
}

def fetch(song):
    print(f"\nAnalyzing: {song}")
    r = httpx.post(f"{API}/analyze", data={"song_ref": song}, timeout=60)
    r.raise_for_status()
    data = r.json()
    analysis = data["analysis"]
    effects = data["effects"]
    print(f"  Analysis done ({len(analysis)} chars)")

    print(f"  Generating audio preview...")
    pr = httpx.post(f"{API}/preview", data={"effects": json.dumps(effects)}, timeout=60)
    pr.raise_for_status()
    preview = pr.json()
    print(f"  Audio done")

    return {
        "song": song,
        "analysis": analysis,
        "effects": effects,
        "dry": preview["dry"],
        "wet": preview["wet"],
    }

def generate():
    demo_path = pathlib.Path(__file__).parent.parent / "frontend" / "src" / "demoData.js"
    content = demo_path.read_text(encoding="utf-8")

    # Parse existing data
    match = re.search(r"const DEMO_DATA = (\[.*\]);", content, re.DOTALL)
    existing = json.loads(match.group(1))

    # Fetch new songs
    new_data = {new: fetch(new) for old, new in REPLACEMENTS.items()}

    # Replace entries
    for i, entry in enumerate(existing):
        for old, new in REPLACEMENTS.items():
            if entry["song"] == old:
                existing[i] = new_data[new]
                print(f"\nReplaced '{old}' with '{new}'")

    demo_path.write_text(
        "// Auto-generated by generate_demo.py - do not edit manually\n"
        "const DEMO_DATA = " + json.dumps(existing, indent=2) + ";\n\n"
        "export default DEMO_DATA;\n",
        encoding="utf-8",
    )
    print(f"\nWritten to {demo_path}")

if __name__ == "__main__":
    generate()
