"""
Run this with the backend already running locally (uvicorn main:app --reload).
It hits /analyze and /preview for each demo song and writes
frontend/src/demoData.js with all the hardcoded results.
"""

import json
import httpx
import pathlib

API = "http://localhost:8000"

SONGS = [
    "Crowbar - Planets Collide",
    "Mac DeMarco - Salad Days",
    "Funkadelic - Maggot Brain",
    "My Bloody Valentine - Only Shallow",
    "Sonic Youth - Teenage Riot",
]

def generate():
    results = []

    for song in SONGS:
        print(f"\nAnalyzing: {song}")

        # Step 1: analyze
        r = httpx.post(f"{API}/analyze", data={"song_ref": song}, timeout=60)
        r.raise_for_status()
        data = r.json()
        analysis = data["analysis"]
        effects = data["effects"]
        print(f"  Analysis done ({len(analysis)} chars)")

        # Step 2: preview
        print(f"  Generating audio preview...")
        pr = httpx.post(
            f"{API}/preview",
            data={"effects": json.dumps(effects)},
            timeout=60,
        )
        pr.raise_for_status()
        preview = pr.json()
        print(f"  Audio done (dry={len(preview['dry'])} chars, wet={len(preview['wet'])} chars)")

        results.append({
            "song": song,
            "analysis": analysis,
            "effects": effects,
            "dry": preview["dry"],
            "wet": preview["wet"],
        })

    # Write output
    out = pathlib.Path(__file__).parent.parent / "frontend" / "src" / "demoData.js"
    out.write_text(
        "// Auto-generated by generate_demo.py - do not edit manually\n"
        "const DEMO_DATA = " + json.dumps(results, indent=2) + ";\n\n"
        "export default DEMO_DATA;\n",
        encoding="utf-8",
    )
    print(f"\nWritten to {out}")

if __name__ == "__main__":
    generate()
